# Generated by Django 4.0.4 on 2022-04-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('cuerpo', models.TextField(verbose_name='')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('autor', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('cuerpo', models.TextField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
